//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Platini.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public Account()
        {
            this.CreditCardDetails = new HashSet<CreditCardDetail>();
            this.Addresses = new HashSet<Address>();
            this.Communications = new HashSet<Communication>();
            this.Companies = new HashSet<Company>();
            this.CustomerUsers = new HashSet<CustomerUser>();
            this.CustomerUsers1 = new HashSet<CustomerUser>();
            this.CustomerSalesPersons = new HashSet<CustomerSalesPerson>();
            this.CustomerSalesPersons1 = new HashSet<CustomerSalesPerson>();
            this.CustomerItemPrices = new HashSet<CustomerItemPrice>();
            this.CustomerOptionalInfoes = new HashSet<CustomerOptionalInfo>();
            this.LoginLogs = new HashSet<LoginLog>();
            this.Orders = new HashSet<Order>();
            this.Orders1 = new HashSet<Order>();
            this.OrderLogs = new HashSet<OrderLog>();
            this.ShowRoomImages = new HashSet<ShowRoomImage>();
            this.Transactions = new HashSet<Transaction>();
            this.ExtraPermissions = new HashSet<ExtraPermission>();
        }
    
        public int AccountId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string UserName { get; set; }
        public string Email { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> LastLoginDate { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateUpdated { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public int RoleId { get; set; }
        public byte[] Password { get; set; }
        public Nullable<bool> IsLocal { get; set; }
        public string FacebookUserId { get; set; }
        public string GoogleId { get; set; }
    
        public virtual Role Role { get; set; }
        public virtual ICollection<CreditCardDetail> CreditCardDetails { get; set; }
        public virtual ICollection<Address> Addresses { get; set; }
        public virtual ICollection<Communication> Communications { get; set; }
        public virtual ICollection<Company> Companies { get; set; }
        public virtual ICollection<CustomerUser> CustomerUsers { get; set; }
        public virtual ICollection<CustomerUser> CustomerUsers1 { get; set; }
        public virtual ICollection<CustomerSalesPerson> CustomerSalesPersons { get; set; }
        public virtual ICollection<CustomerSalesPerson> CustomerSalesPersons1 { get; set; }
        public virtual ICollection<CustomerItemPrice> CustomerItemPrices { get; set; }
        public virtual ICollection<CustomerOptionalInfo> CustomerOptionalInfoes { get; set; }
        public virtual ICollection<LoginLog> LoginLogs { get; set; }
        public virtual ICollection<Order> Orders { get; set; }
        public virtual ICollection<Order> Orders1 { get; set; }
        public virtual ICollection<OrderLog> OrderLogs { get; set; }
        public virtual ICollection<ShowRoomImage> ShowRoomImages { get; set; }
        public virtual ICollection<Transaction> Transactions { get; set; }
        public virtual ICollection<ExtraPermission> ExtraPermissions { get; set; }
    }
}
