//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Platini.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class BackgroundPicture
    {
        public int PictureId { get; set; }
        public string Picture { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateUpdated { get; set; }
        public Nullable<int> SortOrder { get; set; }
        public string Picture_iPhone6 { get; set; }
        public string Picture_iPhone6s { get; set; }
        public string Picture_iPadL { get; set; }
        public string Picture_iPadP { get; set; }
        public string Picture_iPadRL { get; set; }
        public string Picture_iPadRP { get; set; }
    }
}
