//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Platini.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClothesScaleSize
    {
        public ClothesScaleSize()
        {
            this.OrderSizes = new HashSet<OrderSize>();
        }
    
        public int ClothesScaleSizeId { get; set; }
        public int ClothesScaleId { get; set; }
        public int SizeId { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateUpdated { get; set; }
        public Nullable<bool> IsLocal { get; set; }
    
        public virtual ClothesScale ClothesScale { get; set; }
        public virtual ICollection<OrderSize> OrderSizes { get; set; }
        public virtual Size Size { get; set; }
    }
}
