//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Platini.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClothesScale
    {
        public ClothesScale()
        {
            this.OrderScales = new HashSet<OrderScale>();
            this.ClothesScaleSizes = new HashSet<ClothesScaleSize>();
        }
    
        public int ClothesScaleId { get; set; }
        public string Name { get; set; }
        public int ClothesId { get; set; }
        public Nullable<int> FitId { get; set; }
        public Nullable<int> InseamId { get; set; }
        public Nullable<bool> IsOpenSize { get; set; }
        public Nullable<int> InvQty { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateUpdated { get; set; }
        public Nullable<bool> IsLocal { get; set; }
    
        public virtual Cloth Cloth { get; set; }
        public virtual ICollection<OrderScale> OrderScales { get; set; }
        public virtual Fit Fit { get; set; }
        public virtual Inseam Inseam { get; set; }
        public virtual ICollection<ClothesScaleSize> ClothesScaleSizes { get; set; }
    }
}
