//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Platini.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cloth
    {
        public Cloth()
        {
            this.OrderScales = new HashSet<OrderScale>();
            this.OrderSizes = new HashSet<OrderSize>();
            this.ClothesImages = new HashSet<ClothesImage>();
            this.CustomerItemPrices = new HashSet<CustomerItemPrice>();
            this.RelatedClothes = new HashSet<RelatedClothe>();
            this.RelatedClothes1 = new HashSet<RelatedClothe>();
            this.RelatedColors = new HashSet<RelatedColor>();
            this.RelatedColors1 = new HashSet<RelatedColor>();
            this.ClothesScales = new HashSet<ClothesScale>();
        }
    
        public int ClothesId { get; set; }
        public string StyleNumber { get; set; }
        public string Color { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string ClothesDescription { get; set; }
        public int CategoryId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> Clearance { get; set; }
        public int BrandId { get; set; }
        public int SortOrder { get; set; }
        public Nullable<System.DateTime> FutureDeliveryDate { get; set; }
        public int SizeGroupId { get; set; }
        public Nullable<int> IsSent { get; set; }
        public Nullable<decimal> ProductCost { get; set; }
        public Nullable<int> OriginalQty { get; set; }
        public Nullable<decimal> MSRP { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateUpdated { get; set; }
        public string AdminNote { get; set; }
        public Nullable<int> AdjustQty { get; set; }
        public Nullable<System.DateTime> DateChanged { get; set; }
        public string Tags { get; set; }
        public Nullable<decimal> DiscountedMSRP { get; set; }
        public Nullable<decimal> DiscountedPrice { get; set; }
        public string OldStyleNumber { get; set; }
        public Nullable<int> InitialQty { get; set; }
    
        public virtual Brand Brand { get; set; }
        public virtual Category Category { get; set; }
        public virtual ICollection<OrderScale> OrderScales { get; set; }
        public virtual ICollection<OrderSize> OrderSizes { get; set; }
        public virtual SizeGroup SizeGroup { get; set; }
        public virtual ICollection<ClothesImage> ClothesImages { get; set; }
        public virtual ICollection<CustomerItemPrice> CustomerItemPrices { get; set; }
        public virtual ICollection<RelatedClothe> RelatedClothes { get; set; }
        public virtual ICollection<RelatedClothe> RelatedClothes1 { get; set; }
        public virtual ICollection<RelatedColor> RelatedColors { get; set; }
        public virtual ICollection<RelatedColor> RelatedColors1 { get; set; }
        public virtual ICollection<ClothesScale> ClothesScales { get; set; }
    }
}
