//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Platini.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class CreditCardDetail
    {
        public int Id { get; set; }
        public string CCName { get; set; }
        public string CCNumber { get; set; }
        public string CCV { get; set; }
        public string CCExpM { get; set; }
        public string CCExpY { get; set; }
        public int AccountId { get; set; }
    
        public virtual Account Account { get; set; }
    }
}
