//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Platini.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerOptionalInfo1
    {
        public int CustomerOptionalInfoId { get; set; }
        public string SecondEmailId { get; set; }
        public byte[] SecondPassword { get; set; }
        public string BusinessReseller { get; set; }
        public int CustomerType { get; set; }
        public Nullable<int> TermId { get; set; }
        public int AccountId { get; set; }
        public Nullable<int> ShipViaId { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateUpdated { get; set; }
    }
}
