//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Platini.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inseam
    {
        public Inseam()
        {
            this.ClothesScales = new HashSet<ClothesScale>();
            this.ScaleSizeQuantities = new HashSet<ScaleSizeQuantity>();
        }
    
        public int InseamId { get; set; }
        public string Name { get; set; }
        public bool IsActive { get; set; }
        public bool IsDelete { get; set; }
        public int SortOrder { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateUpdated { get; set; }
    
        public virtual ICollection<ClothesScale> ClothesScales { get; set; }
        public virtual ICollection<ScaleSizeQuantity> ScaleSizeQuantities { get; set; }
    }
}
