//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Platini.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderScale
    {
        public System.Guid OrderScaleId { get; set; }
        public System.Guid OrderId { get; set; }
        public int ClothesScaleId { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> PackedQty { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateUpdated { get; set; }
        public Nullable<bool> IsConfirmed { get; set; }
        public Nullable<int> ClothesId { get; set; }
    
        public virtual Cloth Cloth { get; set; }
        public virtual ClothesScale ClothesScale { get; set; }
        public virtual Order Order { get; set; }
    }
}
