//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Platini.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuickBookFailureRecord
    {
        public int Id { get; set; }
        public string FailureFrom { get; set; }
        public int FailureFromId { get; set; }
        public Nullable<bool> SyncStatus { get; set; }
        public string FailureOriginalValue { get; set; }
        public Nullable<System.DateTime> FailureDate { get; set; }
        public string ErrorDetails { get; set; }
    }
}
