//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Platini.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class RelatedColor
    {
        public int RelatedColorId { get; set; }
        public int RelClothesId { get; set; }
        public int ClothesId { get; set; }
        public int CategoryId { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateUpdated { get; set; }
        public bool IsActive { get; set; }
        public bool IsDelete { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Cloth Cloth { get; set; }
        public virtual Cloth Cloth1 { get; set; }
    }
}
