//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Platini.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Role
    {
        public Role()
        {
            this.Accounts = new HashSet<Account>();
            this.RolesPermissions = new HashSet<RolesPermission>();
        }
    
        public int RoleId { get; set; }
        public string RoleName { get; set; }
        public string Alias { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateUpdated { get; set; }
    
        public virtual ICollection<Account> Accounts { get; set; }
        public virtual ICollection<RolesPermission> RolesPermissions { get; set; }
    }
}
