//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Platini.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class SizeGroup
    {
        public SizeGroup()
        {
            this.Clothes = new HashSet<Cloth>();
            this.Sizes = new HashSet<Size>();
        }
    
        public int SizeGroupId { get; set; }
        public string Name { get; set; }
        public int CategoryId { get; set; }
        public bool IsActive { get; set; }
        public bool IsDelete { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateUpdated { get; set; }
        public int SortOrder { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual ICollection<Cloth> Clothes { get; set; }
        public virtual ICollection<Size> Sizes { get; set; }
    }
}
