//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Platini.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Size
    {
        public Size()
        {
            this.ClothesScaleSizes = new HashSet<ClothesScaleSize>();
            this.ScaleSizeQuantities = new HashSet<ScaleSizeQuantity>();
        }
    
        public int SizeId { get; set; }
        public string Name { get; set; }
        public int SizeGroupId { get; set; }
        public bool IsActive { get; set; }
        public bool IsDelete { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateUpdated { get; set; }
        public int SortOrder { get; set; }
        public int CategoryId { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual ICollection<ClothesScaleSize> ClothesScaleSizes { get; set; }
        public virtual ICollection<ScaleSizeQuantity> ScaleSizeQuantities { get; set; }
        public virtual SizeGroup SizeGroup { get; set; }
    }
}
