//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Platini.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int TransactionId { get; set; }
        public System.Guid OrderId { get; set; }
        public int AccountId { get; set; }
        public string TransactionNumber { get; set; }
        public string TransactionType { get; set; }
        public string CardNumber { get; set; }
        public string CVV { get; set; }
        public string CardType { get; set; }
        public int Status { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateUpdated { get; set; }
        public string PayPalId { get; set; }
        public Nullable<bool> IsPayPalActive { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Order Order { get; set; }
    }
}
